name: Docker image
 
on:
  workflow_dispatch:

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: write 
 
env:
  AWS_REGION: eu-west-1
  ROLE_TO_ASSUME: arn:aws:iam::650251701672:role/s3-github
  ECR_REPO: first
     
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          role-to-assume: arn:aws:iam::650251701672:role/s3-github
          aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
 
    - name: Build, tag, and push image to ECR
      run: |
        IMAGE_URI="650251701672.dkr.ecr.eu-west-1.amazonaws.com/bmware:latest"
        docker build -t $IMAGE_URI ./app
        docker push $IMAGE_URI
        echo "image_uri=$IMAGE_URI" >> $GITHUB_ENV 
